service: readthebook-cart-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  deploymentBucket:
    name: readthebook-deployment
    serverSideEncryption: AES256
  environment:
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_PORT: ${env:DATABASE_PORT}
    DATABASE_USERNAME: ${env:DATABASE_USERNAME}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_NAME: ${env:DATABASE_NAME}
    PORT: ${env:PORT}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

plugins:
  - serverless-better-credentials
  - serverless-deployment-bucket
  - serverless-offline
